[profile.default]
solc_version = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200 
evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
  "@chainlink/=lib/chainlink-brownie-contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]