[profile.default]
solc_version = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = "cancun"

remappings = [
  "@chainlink/contracts-ccip/=lib/chainlink-ccip/chains/evm/contracts/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
  "@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]